work_machine = File.exist?(File.expand_path("~/.workmachine"))

tap "buo/cask-upgrade"

mas "Magnet", id: 441258766

cask "1password"
cask "istat-menus"
cask "karabiner-elements"

unless work_machine
  cask "example_install"
end

brew "ack"
brew "coreutils"
brew "gnu-sed"
brew "jq"
brew "kubectl"
brew "yq"
brew "mas"
brew "rg"
brew "erdtree"
brew "wget"
